(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
const UI={healthBar:$('healthBar'),healthValue:$('healthValue'),staminaBar:$('staminaBar'),staminaValue:$('staminaValue'),waveValue:$('waveValue'),scoreValue:$('scoreValue'),objective:$('objective'),combo:$('combo'),loadingOverlay:$('loadingOverlay'),loadingBar:$('loadingBar'),loadingText:$('loadingText'),startOverlay:$('startOverlay'),playButton:$('playButton'),pauseOverlay:$('pauseOverlay'),pauseButton:$('pauseButton'),resumeButton:$('resumeButton'),restartPauseButton:$('restartPauseButton'),endOverlay:$('endOverlay'),endEyebrow:$('endEyebrow'),endTitle:$('endTitle'),endText:$('endText'),endScore:$('endScore'),bestScore:$('bestScore'),restartButton:$('restartButton')};
const H=960;let W=540;const BG='data:image/webp;base64,'+(window.__QZ_BG||'');const HERO='https://cdn.jsdelivr.net/gh/mediarl/CKAD-exercises@bc2d39f21f5705664152f4e9fe5b4eff8351d2e9/quartier-zero/assets/hero.webp';const ENEMY='https://cdn.jsdelivr.net/gh/mediarl/CKAD-exercises@bc2d39f21f5705664152f4e9fe5b4eff8351d2e9/quartier-zero/assets/enemy.webp';
const assets={bg:null,hero:null,enemy:null};const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,rand=(a,b)=>a+Math.random()*(b-a),r=n=>Math.round(n);
const heroFrames={idle:[0,1,2],walk:[3,4,5,6,7,8],attack:[9,10,11,12],hurt:[13,14,15]};const enemyFrames={idle:[0,1,2,3],walk:[4,5,6,7,8,9],attack:[12,13,11,10],hurt:[14,15,16]};
const state={ready:false,running:false,paused:false,score:0,best:0,cameraX:0,gate:Infinity,waveIndex:-1,enemies:[],particles:[],last:0,shake:0,flash:0,combo:0,comboTimer:0};try{state.best=+(localStorage.getItem('qz-best-v4')||0)}catch(_){}
const input={x:0,y:0};const keys={};const joy={id:null};
const player={x:520,y:835,vx:0,vy:0,face:1,hp:100,stamina:100,attackTimer:0,cooldown:0,dodgeTimer:0,invuln:0,hurtTimer:0,anim:'idle',frame:0,frameTime:0,hitDone:false};
const BG_SCALE=H/941, SEG=Math.round(1672*BG_SCALE), WORLD=SEG*4, MIN_Y=775, MAX_Y=878;
const waves=[{trigger:960,gate:1240,count:4,text:'Première embuscade. Nettoie la rue.'},{trigger:SEG+330,gate:SEG+650,count:5,text:'Des renforts arrivent. Tiens la ligne.'},{trigger:SEG*2+330,gate:SEG*2+650,count:6,text:'Troisième vague. Continue.'},{trigger:SEG*3-180,gate:SEG*3+140,count:7,text:'Dernière poussée. Sécurise la sortie.'}];
function resize(){const app=$('app'),rect=app.getBoundingClientRect();W=clamp(Math.round(H*(rect.width/rect.height)),360,560);canvas.width=W;canvas.height=H;ctx.imageSmoothingEnabled=false}resize();addEventListener('resize',resize);
function image(src){return new Promise((ok,fail)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>ok(i);i.onerror=()=>fail(Error('asset'));i.src=src})}
async function load(){const list=[["bg",BG],["hero",HERO],["enemy",ENEMY]];let done=0;try{await Promise.all(list.map(async([k,u])=>{assets[k]=await image(u);done++;const p=Math.round(done/list.length*100);UI.loadingBar.style.width=p+'%';UI.loadingText.textContent='Chargement '+p+' %'}));state.ready=true;UI.loadingOverlay.classList.add('hidden');UI.startOverlay.classList.remove('hidden');UI.objective.textContent='Appuie sur JOUER.';window.__QZ_READY=true}catch(e){console.error(e);UI.loadingText.textContent='Erreur de chargement';UI.loadingText.classList.add('error');window.__QZ_ERROR=String(e)}}
function reset(){Object.assign(state,{running:false,paused:false,score:0,cameraX:0,gate:Infinity,waveIndex:-1,enemies:[],particles:[],last:0,shake:0,flash:0,combo:0,comboTimer:0});waves.forEach(w=>{w.spawned=false;w.cleared=false});Object.assign(player,{x:520,y:835,vx:0,vy:0,face:1,hp:100,stamina:100,attackTimer:0,cooldown:0,dodgeTimer:0,invuln:0,hurtTimer:0,anim:'idle',frame:0,frameTime:0,hitDone:false});hud()}
function start(){if(!state.ready)return;reset();state.running=true;UI.startOverlay.classList.add('hidden');UI.pauseOverlay.classList.add('hidden');UI.endOverlay.classList.add('hidden');UI.objective.textContent='Avance dans la rue.';window.__QZ_STARTED=true}
function makeEnemy(x,y,tier){const c=[{hp:30,speed:162,damage:7},{hp:38,speed:178,damage:9},{hp:50,speed:142,damage:12}][tier%3];return{x,y,vx:0,vy:0,face:-1,hp:c.hp,maxHp:c.hp,speed:c.speed,damage:c.damage,cooldown:rand(650,1200),attackTimer:0,hurtTimer:0,deadTimer:0,anim:'idle',frame:0,frameTime:0,hitDone:false,tier:tier%3,telegraph:0}}
function spawnWave(i){const w=waves[i];w.spawned=true;state.waveIndex=i;state.gate=w.gate;for(let n=0;n<w.count;n++)state.enemies.push(makeEnemy(w.gate+rand(55,280),rand(MIN_Y,MAX_Y),n));UI.objective.textContent=w.text;hud()}
function burst(x,y,color,n=9){for(let i=0;i<n;i++)state.particles.push({x,y,vx:rand(-2.4,2.4),vy:rand(-3.6,-.8),age:0,life:rand(220,420),color})}
function showCombo(){UI.combo.textContent='x'+state.combo;UI.combo.classList.add('show-combo');clearTimeout(showCombo.t);showCombo.t=setTimeout(()=>UI.combo.classList.remove('show-combo'),250)}
function hurtEnemy(e,dmg){if(e.deadTimer>0)return;e.hp-=dmg;e.hurtTimer=190;e.vx=player.face*170;state.score+=100;state.combo++;state.comboTimer=850;showCombo();state.shake=5;burst(e.x,e.y-70,'#ffd463');if(e.hp<=0){e.deadTimer=560;state.score+=250;burst(e.x,e.y-70,'#fff',14)}}
function hurtPlayer(dmg,fromX){if(player.invuln>0)return;player.hp-=dmg;player.hurtTimer=240;player.invuln=520;player.vx=fromX<player.x?190:-190;state.shake=10;state.flash=.16;burst(player.x,player.y-80,'#ff756c',12);navigator.vibrate?.(25);if(player.hp<=0)finish(false)}
function attack(){if(!state.running||state.paused||player.cooldown>0||player.attackTimer>0||player.dodgeTimer>0||player.stamina<9)return;player.attackTimer=280;player.cooldown=255;player.stamina-=9;player.hitDone=false;navigator.vibrate?.(10)}
function dodge(){if(!state.running||state.paused||player.dodgeTimer>0||player.attackTimer>0||player.stamina<19)return;player.dodgeTimer=220;player.invuln=300;player.stamina-=19;player.vx=player.face*560;navigator.vibrate?.(12)}
function setAnim(o,name,dt,isPlayer){if(o.anim!==name){o.anim=name;o.frame=0;o.frameTime=0}const arr=(isPlayer?heroFrames:enemyFrames)[name],dur=name==='attack'?70:name==='hurt'?95:name==='walk'?100:175;o.frameTime+=dt;if(o.frameTime>=dur){o.frameTime=0;o.frame=(o.frame+1)%arr.length}}
function update(dt){if(!state.running||state.paused)return;player.cooldown=Math.max(0,player.cooldown-dt);player.attackTimer=Math.max(0,player.attackTimer-dt);player.dodgeTimer=Math.max(0,player.dodgeTimer-dt);player.invuln=Math.max(0,player.invuln-dt);player.hurtTimer=Math.max(0,player.hurtTimer-dt);state.comboTimer=Math.max(0,state.comboTimer-dt);if(!state.comboTimer)state.combo=0;state.shake=Math.max(0,state.shake-dt*.025);state.flash=Math.max(0,state.flash-dt*.0017);
let ix=input.x+(keys.left?-1:0)+(keys.right?1:0),iy=input.y+(keys.up?-1:0)+(keys.down?1:0),m=Math.hypot(ix,iy);if(m>1){ix/=m;iy/=m}const speed=player.dodgeTimer?570:245,drag=player.attackTimer?.12:.24;player.vx=lerp(player.vx,ix*speed,drag);player.vy=lerp(player.vy,iy*speed*.58,drag);player.x+=player.vx*dt/1000;player.y+=player.vy*dt/1000;player.x=clamp(player.x,120,Math.min(WORLD-140,state.gate));player.y=clamp(player.y,MIN_Y,MAX_Y);if(ix)player.face=ix>0?1:-1;player.stamina=clamp(player.stamina+18*dt/1000,0,100);
if(player.attackTimer>80&&player.attackTimer<150&&!player.hitDone){player.hitDone=true;for(const e of state.enemies){const dx=e.x-player.x,dy=Math.abs(e.y-player.y);if(e.deadTimer<=0&&Math.abs(dx)<100&&dy<62&&(player.face>0?dx>-15:dx<15))hurtEnemy(e,12)}}if(!player.attackTimer)player.hitDone=false;const pa=player.hurtTimer?'hurt':player.attackTimer?'attack':(player.dodgeTimer||Math.abs(player.vx)>24||Math.abs(player.vy)>10)?'walk':'idle';setAnim(player,pa,dt,true);
let activeAttackers=state.enemies.filter(e=>e.deadTimer<=0&&(e.attackTimer>0||e.telegraph>0)).length;for(const e of state.enemies){if(e.deadTimer>0){e.deadTimer-=dt;setAnim(e,'hurt',dt,false);continue}e.cooldown-=dt;e.attackTimer=Math.max(0,e.attackTimer-dt);e.hurtTimer=Math.max(0,e.hurtTimer-dt);const hadTelegraph=e.telegraph>0;e.telegraph=Math.max(0,e.telegraph-dt);if(hadTelegraph&&e.telegraph===0){e.attackTimer=260;e.hitDone=false}const dx=player.x-e.x,dy=player.y-e.y,dist=Math.hypot(dx,dy);e.face=dx>0?1:-1;if(e.hurtTimer){e.x+=e.vx*dt/1000;e.vx*=.86;setAnim(e,'hurt',dt,false);continue}if(e.telegraph>0){setAnim(e,'idle',dt,false);continue}if(e.attackTimer>0){setAnim(e,'attack',dt,false);if(e.attackTimer<115&&!e.hitDone){e.hitDone=true;if(Math.abs(dx)<86&&Math.abs(dy)<60)hurtPlayer(e.damage,e.x)}continue}e.hitDone=false;if(dist<70&&e.cooldown<=0&&activeAttackers<2){e.cooldown=rand(800,1350);e.telegraph=180;e.attackTimer=0;activeAttackers++;continue}if(dist>66){let sx=dx/(dist||1)*e.speed,sy=dy/(dist||1)*e.speed*.58;for(const o of state.enemies){if(o===e||o.deadTimer>0)continue;const ox=e.x-o.x,oy=e.y-o.y,od=Math.hypot(ox,oy);if(od>0&&od<64){const push=(64-od)*3;sx+=ox/od*push;sy+=oy/od*push*.65}}e.x+=sx*dt/1000;e.y+=sy*dt/1000;e.y=clamp(e.y,MIN_Y,MAX_Y);setAnim(e,'walk',dt,false)}else setAnim(e,'idle',dt,false)}
state.enemies=state.enemies.filter(e=>e.deadTimer>0||e.hp>0);for(const p of state.particles){p.age+=dt;p.x+=p.vx;p.y+=p.vy;p.vy+=.12}state.particles=state.particles.filter(p=>p.age<p.life);
const next=waves.findIndex(w=>!w.spawned&&player.x>=w.trigger);if(next>=0)spawnWave(next);waves.forEach((w,i)=>{if(w.spawned&&!w.cleared&&!state.enemies.some(e=>e.deadTimer<=0&&e.hp>0)){w.cleared=true;state.gate=Infinity;state.score+=500;UI.objective.textContent=i===3?'Zone sécurisée. Rejoins la sortie.':'Zone sécurisée. Continue.'}});if(waves.every(w=>w.cleared)&&player.x>WORLD-190)finish(true);state.cameraX=clamp(player.x-W*.38,0,WORLD-W);hud()}
function hud(){UI.healthBar.style.width=clamp(player.hp,0,100)+'%';UI.staminaBar.style.width=clamp(player.stamina,0,100)+'%';UI.healthValue.textContent=Math.max(0,Math.ceil(player.hp));UI.staminaValue.textContent=Math.ceil(player.stamina);UI.waveValue.textContent=Math.max(0,state.waveIndex+1)+'/4';UI.scoreValue.textContent=state.score+' pts'}
function drawFrame(sheet,index,cellW,cellH,cols,x,y,scale,flip){const sx=index%cols*cellW,sy=Math.floor(index/cols)*cellH,dw=r(cellW*scale),dh=r(cellH*scale);ctx.save();if(flip){ctx.translate(r(x),0);ctx.scale(-1,1);ctx.drawImage(sheet,sx,sy,cellW,cellH,-r(dw/2),r(y-dh),dw,dh)}else ctx.drawImage(sheet,sx,sy,cellW,cellH,r(x-dw/2),r(y-dh),dw,dh);ctx.restore()}
function actor(o,isPlayer){const x=r(o.x-state.cameraX),y=r(o.y),arr=(isPlayer?heroFrames:enemyFrames)[o.anim],idx=arr[o.frame%arr.length],scale=isPlayer?.72:.74;ctx.fillStyle='rgba(0,0,0,.38)';ctx.beginPath();ctx.ellipse(x,y+9,isPlayer?30:27,8,0,0,Math.PI*2);ctx.fill();drawFrame(isPlayer?assets.hero:assets.enemy,idx,320,isPlayer?300:260,isPlayer?4:5,x,y,scale,o.face<0);if(!isPlayer&&o.deadTimer<=0){ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(x-24,y-128,48,6);ctx.fillStyle=o.tier===2?'#f06a61':'#ffb44e';ctx.fillRect(x-24,y-128,r(48*clamp(o.hp/o.maxHp,0,1)),6);if(o.telegraph>0){ctx.fillStyle='#ff554d';ctx.font='900 22px system-ui';ctx.fillText('!',x-3,y-145)}}}
function draw(){if(!state.ready)return;ctx.save();if(state.shake)ctx.translate(rand(-state.shake,state.shake),rand(-state.shake*.35,state.shake*.35));for(let i=0;i<4;i++)ctx.drawImage(assets.bg,r(i*SEG-state.cameraX),0,SEG,H);ctx.fillStyle='rgba(5,7,10,.08)';ctx.fillRect(0,790,W,H-790);if(state.gate<Infinity){ctx.fillStyle='rgba(236,74,65,.5)';ctx.fillRect(r(state.gate-state.cameraX),730,7,170)}if(waves.every(w=>w.cleared)){const ex=WORLD-145-state.cameraX;ctx.fillStyle='rgba(72,218,127,.32)';ctx.fillRect(r(ex),720,96,190);ctx.strokeStyle='rgba(215,255,228,.8)';ctx.strokeRect(r(ex),720,96,190);ctx.fillStyle='#fff';ctx.font='900 14px system-ui';ctx.fillText('SORTIE',r(ex)+17,742)}[...state.enemies,player].sort((a,b)=>a.y-b.y).forEach(o=>actor(o,o===player));for(const p of state.particles){ctx.globalAlpha=1-p.age/p.life;ctx.fillStyle=p.color;ctx.fillRect(r(p.x-state.cameraX),r(p.y),3,3)}ctx.globalAlpha=1;if(state.flash){ctx.fillStyle='rgba(255,255,255,'+state.flash+')';ctx.fillRect(0,0,W,H)}ctx.restore()}
function finish(win){state.running=false;state.best=Math.max(state.best,state.score);try{localStorage.setItem('qz-best-v4',state.best)}catch(_){}UI.endOverlay.classList.remove('hidden');UI.endEyebrow.textContent=win?'NIVEAU TERMINÉ':'DÉFAITE';UI.endTitle.innerHTML=win?'RUE<br><em>SÉCURISÉE</em>':'TU AS ÉTÉ<br><em>SUBMERGÉ</em>';UI.endText.textContent=win?'La sortie est dégagée. Le niveau est terminé.':'Rejoue pour reprendre la rue.';UI.endScore.textContent=state.score;UI.bestScore.textContent=state.best}
function loop(t){const dt=Math.min(34,t-(state.last||t));state.last=t;update(dt);draw();requestAnimationFrame(loop)}
function moveJoy(e){const rect=$('joystick').getBoundingClientRect();let dx=e.clientX-rect.left-rect.width/2,dy=e.clientY-rect.top-rect.height/2,max=38,d=Math.hypot(dx,dy);if(d>max){dx*=max/d;dy*=max/d}input.x=dx/max;input.y=dy/max;$('joystickKnob').style.transform=`translate(${dx}px,${dy}px)`}
function stopJoy(e){if(e&&joy.id!==e.pointerId)return;joy.id=null;input.x=input.y=0;$('joystickKnob').style.transform=''}const joyEl=$('joystick');joyEl.onpointerdown=e=>{joy.id=e.pointerId;joyEl.setPointerCapture(e.pointerId);moveJoy(e)};joyEl.onpointermove=e=>{if(joy.id===e.pointerId)moveJoy(e)};joyEl.onpointerup=stopJoy;joyEl.onpointercancel=stopJoy;
UI.playButton.addEventListener('click',start);UI.resumeButton.addEventListener('click',()=>{state.paused=false;UI.pauseOverlay.classList.add('hidden')});UI.restartPauseButton.addEventListener('click',start);UI.restartButton.addEventListener('click',start);UI.pauseButton.addEventListener('click',()=>{if(!state.running)return;state.paused=!state.paused;UI.pauseOverlay.classList.toggle('hidden',!state.paused)});$('attackButton').addEventListener('pointerdown',attack);$('dodgeButton').addEventListener('pointerdown',dodge);
addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=true;if(e.key==='ArrowRight'||e.key==='d')keys.right=true;if(e.key==='ArrowUp'||e.key==='w')keys.up=true;if(e.key==='ArrowDown'||e.key==='s')keys.down=true;if(e.key===' '||e.key==='j')attack();if(e.key==='Shift'||e.key==='k')dodge()});addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=false;if(e.key==='ArrowRight'||e.key==='d')keys.right=false;if(e.key==='ArrowUp'||e.key==='w')keys.up=false;if(e.key==='ArrowDown'||e.key==='s')keys.down=false});
window.__QZ_VERSION='2026-07-11-v8';window.__QZ={state,player,waves,start,spawnWave,attack,dodge};load();requestAnimationFrame(loop);
})();